export interface Round {
  id: number;
  code?: string; // e.g. VQ01
  label: string;
  date: string; // YYYY-MM-DD
  startTime: string; // HH:mm
  endTime: string;   // HH:mm
  checkInOpenTime: string; // HH:mm
  checkInCloseTime: string; // HH:mm
  status: 'cho' | 'dang_dien_ra' | 'hoan_thanh';
  participantIds: string[]; // Eligible participants for this round
  inventoryIds: string[]; // Apartment IDs assigned to this round
  inventoryMode?: 'danh_sach' | 'so_luong'; // How inventory is defined
  inventoryCount?: number; // Quantity if mode is 'so_luong'
  apartmentRightFilter?: 'mua' | 'thue' | 'thue_mua' | 'tat_ca'; // Filter for apartments
  apartmentTypeFilter?: 'uu_tien' | 'thuong' | 'tat_ca'; // Filter for apartments by type
  winners: string[]; // Participant IDs who won in this round
  right: 'mua' | 'thue' | 'thue_mua';
  participantType: 'ut1_4' | 'ut5' | 'thuong'; // Round type: UT1-4, UT5, or Thong Thuong
  // Thời gian đặc biệt
  supervisorDeadlineTime?: string; // HH:mm - Hạn GSV bấm bốc thăm hộ (vòng UT1-4)
  regularRoundStartTime?: string;  // HH:mm - Thời gian bắt đầu vòng thường (vòng UT5)
  resultReleaseMinutes?: number;   // Phút chờ trả kết quả sau khi kết thúc quay
  isAutoGenerated?: boolean;       // Vòng tự sinh từ HS UT5 trượt
  // Ghi đè hiển thị
  displayParticipantCount?: number;
  displayStatus?: string;
  displayStatusColor?: string;
  roundType?: 'uu_tien_trung' | 'uu_tien_trung_truot' | 'thong_thuong'; 
}

export interface ParticipantHistory {
  field: string;
  timestamp: string;
  actor: string;
  note: string;
  oldValue?: string;
  newValue?: string;
  details?: string;
}

export interface Participant {
  id: string; // e.g., HS001
  name: string;
  phone: string;
  cccd: string;
  dob?: string; // Date of Birth
  checkInStatus: boolean;
  checkInTime?: string | null;
  photo: string | null;
  hasWon: boolean;
  drawStatus: 'cho' | 'trung' | 'truot';
  assignedUnit?: string;
  right: 'mua' | 'thue' | 'thue_mua';
  type: 'ut1' | 'ut2' | 'ut3' | 'ut4' | 'ut5' | 'thuong'; // Loại đối tượng
  status: 'hoat_dong' | 'vo_hieu';
  profileStatus: 'hoan_thanh' | 'chua_hoan_thanh';
  documentUrl?: string | null;
  wonRoundLabel?: string;
  isDuplicate: boolean;
  duplicateWith?: string;
  history?: ParticipantHistory[];
  
  // --- PHASE 2 FIELDS ---
  applicationState?: 'nhap' | 'da_nhan' | 'dang_xu_ly' | 'tra_ho_so' | 'cho_ban_cung' | 'hoan_thanh' | 'qua_han_ban_cung';
  groupK?: string;  // Nhom doi tuong K1, K2..
  returnReason?: string; // Ly do bi tra ho so
  hardCopyDueDate?: string; // Han nop ban cung ISO
  hardCopySubmitDate?: string; // Ngay da nop ban cung
  storageArrivalDate?: string; // Ngay nhap kho
  submitTime?: string; // Thoi gian nop online
  processingDeadline?: string; // Han xu ly
  email?: string;
  files?: Array<{ name: string; url: string; category: string; id?: string }>;
  actionLog?: Array<{ time: string; actor: string; action: string; comment?: string }>;
  address?: string;
  
  // Biểu mẫu 02 Data (Phụ lục 02 - BXD)
  form02Data?: {
    registrationRight: 'mua' | 'thue' | 'thue_mua' | '';
    dob?: string;
    currentAddress: string;
    contactPhone: string;
    idNumber09?: string;
    idNumber12?: string;
    idIssuanceDate?: string;
    idIssuancePlace?: string;
    militaryIdNumber?: string; // Số CMT dành cho CBCS quân đội, công an
    permanentAddress: string;
    temporaryAddress?: string;
    
    registrationType: 'moi' | 'chuyen_nhuong';
    oldOwnerName?: string;
    oldOwnerId?: string;
    transferContractDate?: string; // ngày/tháng/năm ký hợp đồng chuyển nhượng

    householdMemberCount?: number; // Số lượng người trong cùng sổ hộ khẩu

    housingStatus: {
      noHome: boolean;
      lowArea: boolean;
      farAway: boolean;
      other: boolean;
    };

    // Đối tượng theo Điều 76 Luật Nhà ở 2023
    subjectCategory: {
      nguoiCoCong: boolean;
      ngheoNongThon: boolean;
      ngheoThienTai: boolean;
      ngheoDoThi: boolean;
      thuNhapThap: boolean;
      congNhan: boolean;
      lucLuongVuTrang: boolean;
      canBoCongChuc: boolean;
      traNhaCongVu: boolean;
      thuHoiDat: boolean;
      hocSinhSinhVien: boolean;
      doanhNghiep: boolean;
    };

    familyMembers: Array<{
      id: string;
      name: string;
      cccd09?: string;
      cccd12?: string;
      relationship: string;
    }>;

    submittedAt?: string;
    formVersion?: string; // e.g. "2023-BXD"
  };

  // Administration
  assignedOfficerId?: string; 

  // Document-level review (Phase 2)
  documentStatuses?: Record<string, 'approved' | 'rejected' | 'pending'>;
  documentComments?: Record<string, string>;

  // --- DEMO AUTH FIELDS ---
  password?: string;
  passwordSet?: boolean;
}

export interface ApartmentHistory {
  field: string;
  timestamp: string;
  actor: string;
  note: string;
  oldValue?: string;
  newValue?: string;
  details?: string;
}

export interface Apartment {
  id: string; // e.g., C010203
  block: string; // 01
  floor: string; // 02
  unit: string;  // 03
  area: number;
  orientation: string;
  status: 'trong' | 'da_ban'; // Trống / Đã bán
  ownerId?: string;
  right: 'mua' | 'thue' | 'thue_mua'; // Quyền: Mua, Thuê, Thuê-Mua
  type: 'uu_tien' | 'thuong'; // Loại: Ưu tiên, Thông thường
  history?: ApartmentHistory[];
}

export interface SystemAccount {
  id: string;
  username: string;
  displayName: string;
  password?: string;
  role: string; // References Role.id
  status: 'hoat_dong' | 'vo_hieu';
  lastLogin?: string;
}

export interface Role {
  id: string;
  name: string;
  description: string;
  permissions: string[];
  isSystem?: boolean;
}

export interface AccountLog {
  id: string;
  timestamp: string;
  actorId: string;
  actorName: string;
  action: 'tao' | 'cap_nhat' | 'xoa' | 'dang_nhap' | 'doi_trang_thai';
  targetAccountId?: string;
  targetAccountName?: string;
  details: string;
}